### ISSUE TITLE
Bulk edit

### ISSUE THREAD

**Issue by linzr** [cs3226-2017-3c/lab05#14]
> Give another view for editing the student data. For now, most groups show edit feature one student at a time, as that is what was asked in Lab4. However, notice that for example after a CS3233 Mini Contest has been completed, the lecturer has to click N edit buttons, update that particular Mini Contest scores of all students, then click N update buttons, one after another... This should be simplified by having another view where the lecturer can edit/upload all N scores of a certain Mini Contest, a certain Homework, a certain Kattis set, etc in three steps only: click to open this new view, enter N data, and then click one single update button only. Do you need to change your underlying database schema or is there another way?

**Comment by davidzhao800** [comment]
implemented by f7b9dbe

**Comment by linzr** [comment]
Can be closed.
