### ISSUE TITLE
Progress over time feature

### ISSUE THREAD

**Issue by linzr** [cs3226-2017-3c/lab05#15]
> Add "progress over time" feature. Currently the landing page/the ranklist of our ranklist app shows the latest scores of every student at this point of time. What if we want to show progress over time (e.g. NUS week 1 to week 13)? We may have to record more data or put timestamp-related features in our database. Display this progress over time as a line chart (use whatever line chart) where the y-axis should be the sum scores and the x-axis should be the time (e.g. 13 ticks: Week 1 to Week 13). Give option to turn on/off certain students in this "progress over time" chart. In my mind, I am thinking of this. Decide what changes (another migration) that you have to do to your underlying database scheme (if your group has used it earlier) or to think from scratch to support this feature if your group has not used database before.

**Comment by linzr** [comment]
History mode has been created.

**Comment by luckyxkw** [comment]
[9023ffd] the history chart is drawn, but I feel it is too messy.
want to make a form for users to choose students to display history chart instead of displaying all
